# netlify.toml

[build]
# Use the root directory as the publish directory
publish = "."
# No build command needed for static files
command = "echo No build needed"

[[headers]]
# Apply headers to all .js files
for = "*.js"
[headers.values]
  Access-Control-Allow-Origin = "*"
  Content-Type = "application/javascript"
